language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support

jdk:
    - oraclejdk7

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10

notifications:
  email: false

sudo: required

cache:
  directories:
    - $HOME/.gradle

before_install:
 - rm -f gradle.properties
 - cp gradle.properties.example gradle.properties
 - chmod +x ./gradlew

script:
    - ./gradlew assembleDebug --stacktrace
